# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger_hunt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scavengerhunt',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
            preserve_default=False,
        ),
    ]
