# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger_hunt', '0002_scavengerhunt_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scavengerhunt',
            options={'ordering': ('time_created',)},
        ),
        migrations.AddField(
            model_name='scavengerhunt',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
