# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger_hunt', '0004_puzzle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scavengerhunt',
            name='completed',
        ),
    ]
